// Cytat dnia — deterministyczny (ten sam przez cały dzień, zmienia się
// o północy), bez sieci i bez losowości między renderami.
// Format wpisu: t = treść, a = autor (null: autor nieznany), y = rok/epoka
// (string, null gdy nieznany). Pokazywany na ekranie intra przed sesją.
export const QUOTES = [
  // — kulturystyka i siłownia —
  { t: "Siła nie bierze się z wygrywania. Budują ją zmagania.", a: "Arnold Schwarzenegger", y: "1977" },
  { t: "Ostatnie trzy albo cztery powtórzenia — to one budują mięśnie.", a: "Arnold Schwarzenegger", y: "1977" },
  { t: "Trenuj ciężko, ale przede wszystkim trenuj mądrze.", a: "Arnold Schwarzenegger", y: "1985" },
  { t: "Opór, którego nie pokonasz dzisiaj, pokonasz jutro — jeśli wrócisz.", a: "Arnold Schwarzenegger", y: null },
  { t: "Każdy chce być kulturystą, ale nikt nie chce dźwigać naprawdę ciężkich ciężarów.", a: "Ronnie Coleman", y: "2000" },
  { t: "Nie ma nic lżejszego niż ciężar, którego nigdy nie podniosłeś.", a: "Ronnie Coleman", y: null },
  { t: "Ból to słabość opuszczająca ciało.", a: null, y: null },
  { t: "Zbuduj ciało, któremu podziękujesz za dziesięć lat.", a: null, y: null },
  { t: "Siłownia niczego nie obiecuje. Ona tylko oddaje to, co w nią włożysz.", a: null, y: null },
  { t: "Mistrzostwo to suma tysięcy powtórzeń, których nikt nie widział.", a: null, y: null },
  { t: "Nie musisz mieć motywacji. Musisz mieć plan i przyjść.", a: null, y: null },
  { t: "Ciężko na treningu, lekko w życiu.", a: null, y: null },
  { t: "Najtrudniejszy ciężar do podniesienia to własne cztery litery z kanapy.", a: null, y: null },
  { t: "Jedyny zły trening to ten, który się nie odbył.", a: null, y: null },
  { t: "Twoje ciało wytrzyma prawie wszystko. To umysł trzeba przekonać.", a: null, y: null },
  { t: "Silny kręgosłup nosi lekką głowę.", a: null, y: null },
  { t: "Nie licz powtórzeń. Zacznij liczyć dopiero wtedy, gdy zaczyna boleć.", a: "Muhammad Ali", y: "1974" },
  { t: "Żelazo nigdy nie kłamie. Sto kilo to zawsze sto kilo.", a: "Henry Rollins", y: "1994" },
  { t: "Żelazo to najlepszy antydepresant: zawsze jest na miejscu i nigdy nie ma wymówek.", a: "Henry Rollins", y: "1994" },
  { t: "Dyscyplina to najczystsza forma miłości do samego siebie.", a: "Mike Tyson", y: "2020" },
  { t: "Wszystko, co masz, zdobywasz ciężką pracą — talent to dopiero zaproszenie.", a: "Dorian Yates", y: null },
  { t: "Intensywność buduje mistrzów. Objętość buduje wytrwałych. Konsekwencja buduje obu.", a: null, y: null },
  { t: "Nie skracaj ruchu. Życie i tak będzie skracać za ciebie.", a: "Tom Platz", y: null },
  { t: "Głowa poddaje się pierwsza, nie nogi. Naucz ją milczeć.", a: null, y: null },

  // — boks, sporty walki —
  { t: "Nie licz dni. Spraw, żeby dni się liczyły.", a: "Muhammad Ali", y: "1974" },
  { t: "Mistrzowie nie powstają na siłowni. Powstają z pragnienia, marzenia i wizji.", a: "Muhammad Ali", y: "1971" },
  { t: "Nienawidziłem każdej minuty treningu, ale mówiłem sobie: nie rezygnuj. Cierp teraz i żyj resztę życia jak mistrz.", a: "Muhammad Ali", y: "1965" },
  { t: "To tylko praca. Trawa rośnie, ptaki latają, fale biją o piasek. Ja biję ludzi.", a: "Muhammad Ali", y: "1977" },
  { t: "Każdy ma plan, dopóki nie dostanie w twarz.", a: "Mike Tyson", y: "1987" },
  { t: "Bohaterowie i tchórze czują dokładnie ten sam strach. Różni ich to, co z nim robią.", a: "Cus D'Amato", y: "1985" },
  { t: "Mistrz to ktoś, kto wstaje, kiedy nie może.", a: "Jack Dempsey", y: "1950" },
  { t: "Nie modlę się o lekkie życie. Modlę się o siłę, by unieść to trudne.", a: "Bruce Lee", y: "1971" },
  { t: "Nie boję się człowieka, który ćwiczył dziesięć tysięcy kopnięć. Boję się tego, który jedno kopnięcie ćwiczył dziesięć tysięcy razy.", a: "Bruce Lee", y: "1972" },
  { t: "Cel nie zawsze jest po to, by go osiągnąć. Często służy temu, by było do czego celować.", a: "Bruce Lee", y: "1973" },
  { t: "Zwycięzca to przegrany, który spróbował jeszcze raz.", a: "George Foreman", y: null },
  { t: "Tu nie ma talentu. To jest ciężka praca.", a: "Conor McGregor", y: "2015" },
  { t: "Na treningu jesteś wolny od wszystkiego. Zostaje tylko robota.", a: "Chadzi Muchamiedow", y: null },
  { t: "Dyscyplina robi swoje wtedy, kiedy motywacja śpi.", a: null, y: null },
  { t: "Twarde treningi, łatwe walki.", a: "Aleksandr Suworow", y: "1795" },

  // — sport: legendy —
  { t: "Spudłowałem w karierze ponad dziewięć tysięcy rzutów. Przegrałem prawie trzysta meczów. I właśnie dlatego wygrywam.", a: "Michael Jordan", y: "1997" },
  { t: "Ograniczenia, jak lęki, są często tylko iluzją.", a: "Michael Jordan", y: "2009" },
  { t: "Grałem, jakby każdy mecz był moim ostatnim.", a: "Kobe Bryant", y: "2015" },
  { t: "Najważniejsze to spróbować zainspirować ludzi, by w tym, co robią, byli wielcy.", a: "Kobe Bryant", y: "2008" },
  { t: "Ciężka praca wygrywa z talentem, kiedy talent nie pracuje ciężko.", a: "Tim Notke", y: null },
  { t: "Tracisz sto procent strzałów, których nie oddasz.", a: "Wayne Gretzky", y: "1983" },
  { t: "Sukces to nie przypadek. To ciężka praca, wytrwałość, nauka, poświęcenie i miłość do tego, co robisz.", a: "Pelé", y: "1977" },
  { t: "Im ciężej pracuję, tym więcej mam szczęścia.", a: "Gary Player", y: "1962" },
  { t: "Trenowałem cztery lata, żeby przebiec dziewięć sekund.", a: "Usain Bolt", y: "2012" },
  { t: "Nie da się postawić granicy niczemu. Im więcej marzysz, tym dalej zajdziesz.", a: "Michael Phelps", y: "2008" },
  { t: "Umiejętności są tanie. Pasja jest bezcenna.", a: null, y: null },
  { t: "Ptak lata, ryba pływa, człowiek biegnie.", a: "Emil Zátopek", y: "1952" },
  { t: "Jeśli chcesz coś wygrać, przebiegnij sto metrów. Jeśli chcesz coś przeżyć — przebiegnij maraton.", a: "Emil Zátopek", y: "1957" },
  { t: "Dać z siebie mniej niż wszystko to poświęcić dar.", a: "Steve Prefontaine", y: "1970" },
  { t: "Żaden człowiek nie ma limitu.", a: "Eliud Kipchoge", y: "2017" },
  { t: "Tylko zdyscyplinowani są w życiu naprawdę wolni.", a: "Eliud Kipchoge", y: "2019" },
  { t: "Złote medale nie są ze złota. Są z potu, determinacji i rzadkiego stopu zwanego charakterem.", a: "Dan Gable", y: "1972" },
  { t: "Wygrywanie to nawyk. Niestety, przegrywanie też.", a: "Vince Lombardi", y: "1967" },
  { t: "Nie liczy się to, czy upadniesz. Liczy się, czy wstaniesz.", a: "Vince Lombardi", y: "1968" },
  { t: "Perfekcja jest nieosiągalna. Ale goniąc ją, łapiemy doskonałość.", a: "Vince Lombardi", y: "1959" },
  { t: "Zrób z każdego dnia swoje arcydzieło.", a: "John Wooden", y: "1972" },
  { t: "Nie pozwól, by to, czego nie potrafisz, przeszkodziło ci w tym, co potrafisz.", a: "John Wooden", y: "1972" },
  { t: "Charakter to to, kim jesteś, gdy nikt nie patrzy.", a: "John Wooden", y: "1972" },
  { t: "Każdy strike przybliża mnie do home runa.", a: "Babe Ruth", y: "1928" },
  { t: "Mistrzowie grają, aż zagrają dobrze.", a: "Billie Jean King", y: "1982" },
  { t: "Presja to przywilej.", a: "Billie Jean King", y: "2008" },
  { t: "Mój przeciwnik to ja sam sprzed tygodnia.", a: null, y: null },
  { t: "Nigdy nie przegrywam. Albo wygrywam, albo się uczę.", a: "Nelson Mandela", y: null },
  { t: "Zawsze wydaje się niemożliwe, dopóki nie zostanie zrobione.", a: "Nelson Mandela", y: "1994" },
  { t: "Biegnij, kiedy możesz, idź, kiedy musisz, czołgaj się, jeśli trzeba. Tylko nigdy się nie zatrzymuj.", a: "Dean Karnazes", y: "2006" },
  { t: "Ból jest tymczasowy. Rezygnacja zostaje na zawsze.", a: "Lance Armstrong", y: "2000" },
  { t: "Rekordy są po to, żeby je bić.", a: null, y: null },
  { t: "Talent to tylko punkt startu.", a: "Robert Lewandowski", y: "2016" },
  { t: "Marzenia się nie spełniają. Marzenia się spełnia.", a: "Robert Lewandowski", y: "2015" },
  { t: "Wygrywa ten, kto najdłużej potrafi cierpieć w milczeniu.", a: null, y: null },
  { t: "Musisz oczekiwać od siebie rzeczy wielkich, zanim będziesz w stanie je zrobić.", a: "Michael Jordan", y: "1994" },
  { t: "Nie gram przeciwko rywalom. Gram przeciwko własnym granicom.", a: "Rafael Nadal", y: "2011" },
  { t: "Przegrana boli bardziej, niż cieszy wygrana. I to ona uczy.", a: "Rafael Nadal", y: "2011" },
  { t: "Trzeba wierzyć w siebie, gdy nikt inny nie wierzy — to czyni cię zwycięzcą od razu.", a: "Venus Williams", y: "2002" },
  { t: "Wielkość to zbiór małych rzeczy robionych dobrze każdego dnia.", a: "Ray Lewis", y: "2013" },
  { t: "Dziś zrobię to, czego inni nie chcą, by jutro mieć to, czego inni nie mają.", a: "Jerry Rice", y: null },
  { t: "Zwycięstwo jest zarezerwowane dla tych, którzy są gotowi zapłacić jego cenę.", a: "Sun Tzu", y: "V w. p.n.e." },

  // — stoicy i klasycy —
  { t: "Nie dlatego nie próbujemy, że rzeczy są trudne. Rzeczy są trudne, bo nie próbujemy.", a: "Seneka", y: "ok. 64" },
  { t: "Los prowadzi chętnych, opornych ciągnie.", a: "Seneka", y: "ok. 64" },
  { t: "Cierpimy częściej w wyobraźni niż w rzeczywistości.", a: "Seneka", y: "ok. 63" },
  { t: "Każda noc jest początkiem nowego dnia. Każdy trening — nowego ciała.", a: null, y: null },
  { t: "Masz władzę nad swoim umysłem, nie nad zdarzeniami. Uświadom to sobie, a znajdziesz siłę.", a: "Marek Aureliusz", y: "ok. 170" },
  { t: "Przeszkoda w działaniu przyspiesza działanie. To, co stoi na drodze, staje się drogą.", a: "Marek Aureliusz", y: "ok. 170" },
  { t: "Nie marnuj reszty życia na rozmyślanie o innych. Rób swoje.", a: "Marek Aureliusz", y: "ok. 170" },
  { t: "O poranku, gdy nie chce ci się wstać, pomyśl: budzę się do roboty człowieka.", a: "Marek Aureliusz", y: "ok. 170" },
  { t: "Żaden człowiek nie ma prawa być amatorem w sprawach treningu ciała. Wstyd zestarzeć się, nie zobaczywszy piękna i siły, do których jest zdolne.", a: "Sokrates", y: "ok. 370 p.n.e." },
  { t: "Najpierw powiedz sobie, kim chcesz być. Potem rób, co trzeba.", a: "Epiktet", y: "ok. 108" },
  { t: "Żadna wielka rzecz nie powstaje nagle — tak jak kiść winogron albo figa.", a: "Epiktet", y: "ok. 108" },
  { t: "Nie tłumacz swojej filozofii. Ucieleśnij ją.", a: "Epiktet", y: "ok. 108" },
  { t: "Podróż tysiąca mil zaczyna się od jednego kroku.", a: "Laozi", y: "VI w. p.n.e." },
  { t: "Nie ma znaczenia, jak wolno idziesz, dopóki się nie zatrzymujesz.", a: "Konfucjusz", y: "ok. 500 p.n.e." },
  { t: "Nasza największa chwała nie polega na tym, że nigdy nie upadamy, lecz na tym, że podnosimy się za każdym razem.", a: "Konfucjusz", y: "ok. 500 p.n.e." },
  { t: "Jesteśmy tym, co robimy wielokrotnie. Doskonałość nie jest więc czynem, lecz nawykiem.", a: "Will Durant", y: "1926" },
  { t: "Poznaj wroga i poznaj siebie, a stu bitew się nie ulękniesz.", a: "Sun Tzu", y: "V w. p.n.e." },
  { t: "Dziś zwyciężaj siebie z wczoraj. Jutro zwyciężaj słabszych od siebie.", a: "Miyamoto Musashi", y: "1645" },
  { t: "Tysiąc dni treningu, by się nauczyć. Dziesięć tysięcy, by oszlifować.", a: "Miyamoto Musashi", y: "1645" },
  { t: "Co mnie nie zabije, to mnie wzmocni.", a: "Friedrich Nietzsche", y: "1888" },
  { t: "Kto ma po co żyć, zniesie prawie każde jak.", a: "Friedrich Nietzsche", y: "1888" },
  { t: "Jeszcze się uczę.", a: "Michał Anioł", y: "ok. 1560" },

  // — wynalazcy, twórcy, liderzy —
  { t: "Nie poniosłem porażki. Znalazłem dziesięć tysięcy sposobów, które nie działają.", a: "Thomas Edison", y: "1910" },
  { t: "Geniusz to jeden procent inspiracji i dziewięćdziesiąt dziewięć procent potu.", a: "Thomas Edison", y: "1903" },
  { t: "Wielu życiowych rozbitków to ludzie, którzy nie zdawali sobie sprawy, jak blisko sukcesu byli, kiedy się poddali.", a: "Thomas Edison", y: null },
  { t: "Czy myślisz, że potrafisz, czy że nie potrafisz — masz rację.", a: "Henry Ford", y: "1947" },
  { t: "Porażka to po prostu okazja, by zacząć jeszcze raz — tym razem mądrzej.", a: "Henry Ford", y: "1922" },
  { t: "Życie jest jak jazda na rowerze. Żeby utrzymać równowagę, musisz się poruszać naprzód.", a: "Albert Einstein", y: "1930" },
  { t: "Nie oceniaj każdego dnia po plonach, które zebrałeś, ale po ziarnach, które zasiałeś.", a: "Robert Louis Stevenson", y: "1885" },
  { t: "Sukces to przechodzenie od porażki do porażki bez utraty entuzjazmu.", a: "Winston Churchill", y: null },
  { t: "Nigdy, nigdy, nigdy się nie poddawaj.", a: "Winston Churchill", y: "1941" },
  { t: "Jeśli przechodzisz przez piekło — idź dalej.", a: "Winston Churchill", y: null },
  { t: "Liczy się nie krytyk, lecz człowiek na arenie — z twarzą umazaną kurzem, potem i krwią.", a: "Theodore Roosevelt", y: "1910" },
  { t: "Rób, co możesz, tym, co masz, tam, gdzie jesteś.", a: "Theodore Roosevelt", y: "1913" },
  { t: "Nikt nie może sprawić, byś czuł się gorszy, bez twojej zgody.", a: "Eleanor Roosevelt", y: "1937" },
  { t: "Przyszłość należy do tych, którzy wierzą w piękno swoich marzeń.", a: "Eleanor Roosevelt", y: null },
  { t: "Rób każdego dnia jedną rzecz, która cię przeraża.", a: "Eleanor Roosevelt", y: null },
  { t: "Twój czas jest ograniczony, więc nie marnuj go na życie cudzym życiem.", a: "Steve Jobs", y: "2005" },
  { t: "Jedyny sposób na wielką robotę to kochać to, co się robi.", a: "Steve Jobs", y: "2005" },
  { t: "Sposób, żeby zacząć, to przestać gadać i zacząć robić.", a: "Walt Disney", y: null },
  { t: "Wszystkie nasze marzenia mogą się spełnić — jeśli mamy odwagę za nimi iść.", a: "Walt Disney", y: null },
  { t: "Sekret posuwania się naprzód to zacząć.", a: "Mark Twain", y: null },
  { t: "Za dwadzieścia lat bardziej będziesz żałował tego, czego nie zrobiłeś, niż tego, co zrobiłeś.", a: "H. Jackson Brown", y: "1990" },
  { t: "Niczego w życiu nie należy się bać, należy to tylko zrozumieć.", a: "Maria Skłodowska-Curie", y: "1937" },
  { t: "Najtrudniej jest zdecydować się działać. Reszta to tylko upór.", a: "Amelia Earhart", y: "1937" },
  { t: "To, co za nami, i to, co przed nami, to drobiazgi wobec tego, co jest w nas.", a: "Ralph Waldo Emerson", y: null },
  { t: "Nie idź tam, dokąd prowadzi ścieżka. Idź tam, gdzie jej nie ma, i zostaw ślad.", a: "Ralph Waldo Emerson", y: null },
  { t: "Pewnie krocz w stronę swoich marzeń. Żyj życiem, które sobie wyobraziłeś.", a: "Henry David Thoreau", y: "1854" },
  { t: "Cokolwiek potrafisz zrobić albo marzysz, że potrafisz — zacznij. W śmiałości jest geniusz, siła i magia.", a: "William H. Murray", y: "1951" },
  { t: "Człowiek, który przenosił góry, zaczynał od małych kamieni.", a: null, y: null },

  // — trenerzy mentalni, pisarze o nawykach —
  { t: "Nie musisz być wielki, żeby zacząć. Musisz zacząć, żeby być wielki.", a: "Zig Ziglar", y: "1975" },
  { t: "Motywacja nie jest na zawsze. Kąpiel też nie — dlatego zaleca się ją codziennie.", a: "Zig Ziglar", y: "1975" },
  { t: "Sukces to suma małych wysiłków powtarzanych dzień po dniu.", a: "Robert Collier", y: "1926" },
  { t: "Nie życz sobie, żeby było łatwiej. Życz sobie, żebyś był lepszy.", a: "Jim Rohn", y: "1981" },
  { t: "Dyscyplina waży gramy, żal waży tony.", a: "Jim Rohn", y: "1981" },
  { t: "Jesteś średnią pięciu osób, z którymi spędzasz najwięcej czasu.", a: "Jim Rohn", y: "1985" },
  { t: "Motywacja cię uruchamia, nawyk trzyma cię w ruchu.", a: "Jim Ryun", y: null },
  { t: "Nie rezygnuj z celu tylko dlatego, że wymaga czasu. Czas i tak upłynie.", a: "Earl Nightingale", y: "1956" },
  { t: "Stajesz się tym, o czym myślisz.", a: "Earl Nightingale", y: "1956" },
  { t: "Każdy postęp odbywa się poza strefą komfortu.", a: "Michael John Bobak", y: null },
  { t: "Nie wznosisz się do poziomu swoich celów. Spadasz do poziomu swoich systemów.", a: "James Clear", y: "2018" },
  { t: "Nawyki to procent składany samodoskonalenia.", a: "James Clear", y: "2018" },
  { t: "Każde działanie jest głosem na osobę, którą chcesz się stać.", a: "James Clear", y: "2018" },
  { t: "Lepszy o jeden procent każdego dnia — po roku jesteś trzydzieści siedem razy lepszy.", a: "James Clear", y: "2018" },
  { t: "Grit to wytrwałość i pasja w dążeniu do bardzo odległych celów.", a: "Angela Duckworth", y: "2016" },
  { t: "W ustalonym umyśle porażka to wyrok. W rozwojowym — informacja.", a: "Carol Dweck", y: "2006" },
  { t: "Jeszcze nie umiem — to najpotężniejsze słowa w nauce.", a: "Carol Dweck", y: "2014" },
  { t: "Dyscyplina równa się wolność.", a: "Jocko Willink", y: "2017" },
  { t: "Nie masz ochoty? Właśnie dlatego idź.", a: "Jocko Willink", y: "2017" },
  { t: "Bądź twardszy niż twoje wymówki.", a: "David Goggins", y: "2018" },
  { t: "Kiedy myślisz, że jesteś skończony, jesteś dopiero na czterdziestu procentach możliwości.", a: "David Goggins", y: "2018" },
  { t: "Zwykłe rzeczy robione konsekwentnie dają niezwykłe rezultaty.", a: "Keith Cunningham", y: null },
  { t: "Jeśli chcesz zmienić świat, zacznij od posłania łóżka.", a: "William H. McRaven", y: "2014" },
  { t: "Ciało robi to, co każe mu umysł wytrenowany przez charakter.", a: null, y: null },
  { t: "Amatorzy czekają na natchnienie. Reszta po prostu wstaje i idzie do roboty.", a: "Stephen King", y: "2000" },
  { t: "Zaczynaj z wizją końca.", a: "Stephen Covey", y: "1989" },
  { t: "Rzeczy najważniejsze nigdy nie mogą być na łasce rzeczy błahych.", a: "Johann Wolfgang von Goethe", y: null },
  { t: "Zwycięzcy to zwykli ludzie z niezwykłą determinacją.", a: null, y: null },
  { t: "Jeśli to ważne, znajdziesz sposób. Jeśli nie — znajdziesz wymówkę.", a: "Ryan Blair", y: "2011" },
  { t: "Cel bez planu jest tylko życzeniem.", a: "Antoine de Saint-Exupéry", y: "1948" },
  { t: "Nie mierz się z innymi. Prawdziwa szlachetność to być lepszym od siebie z wczoraj.", a: "Ernest Hemingway", y: null },
  { t: "Świat łamie każdego, a potem niektórzy są mocni w miejscach złamania.", a: "Ernest Hemingway", y: "1929" },
  { t: "Odwaga to wdzięk pod presją.", a: "Ernest Hemingway", y: "1926" },

  // — film i kultura —
  { t: "Nie chodzi o to, jak mocno uderzasz. Chodzi o to, ile możesz przyjąć i iść dalej.", a: "Rocky Balboa", y: "2006" },
  { t: "Każdy mistrz był kiedyś pretendentem, który nie chciał się poddać.", a: "Rocky Balboa", y: "1976" },
  { t: "Rób albo nie rób. Nie ma próbowania.", a: "Yoda", y: "1980" },
  { t: "Wielka siła to wielka odpowiedzialność — także wobec własnego zdrowia.", a: null, y: null },
  { t: "Strach nie istnieje w tym dojo, prawda?", a: "Karate Kid", y: "1984" },
  { t: "Zwycięstwo lubi przygotowanych.", a: null, y: null },

  // — anonimowe prawdy z siłowni —
  { t: "Ciało osiąga to, w co wierzy umysł.", a: null, y: null },
  { t: "Dyscyplina to robienie tego, czego nie chcesz, żeby osiągnąć to, czego chcesz.", a: null, y: null },
  { t: "Nie porównuj się z innymi. Porównuj się z sobą sprzed miesiąca.", a: null, y: null },
  { t: "Nie chodzi o to, by być najlepszym. Chodzi o to, by być lepszym niż wczoraj.", a: null, y: null },
  { t: "Siła rośnie w chwilach, gdy myślisz, że nie dasz rady — a mimo to nie odpuszczasz.", a: null, y: null },
  { t: "Twoje jedyne ograniczenie to ty sam.", a: null, y: null },
  { t: "Za miesiąc podziękujesz sobie za dzisiaj.", a: null, y: null },
  { t: "Nie musisz być szybki. Wystarczy, że nie staniesz.", a: null, y: null },
  { t: "Trening to spotkanie z lepszą wersją siebie. Nie każ jej czekać.", a: null, y: null },
  { t: "Pot to tłuszcz, który płacze.", a: null, y: null },
  { t: "Nie ma windy na szczyt. Są tylko schody.", a: null, y: null },
  { t: "Kiedy nogi odmawiają, biegnij sercem.", a: null, y: null },
  { t: "Rozgrzewka to umowa z ciałem: ja o ciebie dbam, ty mnie nie zawodzisz.", a: null, y: null },
  { t: "Forma odchodzi w tydzień, charakter zostaje na lata.", a: null, y: null },
  { t: "Silne ciało to najtańsza polisa na życie.", a: null, y: null },
  { t: "Zmęczenie mija. Duma zostaje.", a: null, y: null },
  { t: "Jesteś o jeden trening bliżej celu albo o jedną wymówkę dalej.", a: null, y: null },
  { t: "Woda, sen, białko, plan. Reszta to szczegóły.", a: null, y: null },
  { t: "Trenuj, jakby nikt nie patrzył. Wyglądaj, jakby patrzyli wszyscy.", a: null, y: null },
  { t: "Sto procent treningów, na które poszedłeś, było lepsze od tych, które odpuściłeś.", a: null, y: null },
  { t: "Mięśnie rosną w łóżku. Ale tylko po treningu.", a: null, y: null },
  { t: "Progres to nie przypadek. To decyzja podejmowana codziennie.", a: null, y: null },
  { t: "Słaby dzień to nie słaby rok. Wracaj jutro.", a: null, y: null },
  { t: "Nie przerywaj serii. Ani tej na ławce, ani tej w kalendarzu.", a: null, y: null },
  { t: "Ciężar, który dziś wydaje się niemożliwy, za rok będzie rozgrzewką.", a: null, y: null },
  { t: "Wymówki nie palą kalorii.", a: null, y: null },
  { t: "Zacznij tam, gdzie jesteś. Użyj tego, co masz. Zrób, co możesz.", a: "Arthur Ashe", y: "1988" },
  { t: "Nigdy nie jest za późno, by być tym, kim mogłeś być.", a: "George Eliot", y: null },
  { t: "Najlepszy moment na zasadzenie drzewa był dwadzieścia lat temu. Drugi najlepszy jest teraz.", a: null, y: null },
  { t: "Trudne drogi często prowadzą do pięknych miejsc.", a: null, y: null },
  { t: "Kropla drąży skałę nie siłą, lecz częstym padaniem.", a: "Owidiusz", y: "ok. 10" },
  { t: "Szczęście sprzyja odważnym.", a: "Wergiliusz", y: "ok. 19 p.n.e." },
  { t: "Przez ciernie do gwiazd.", a: null, y: "sentencja łacińska" },
  { t: "W zdrowym ciele zdrowy duch.", a: "Juwenalis", y: "ok. 100" },
  { t: "Zwyciężaj siebie — to zwycięstwo największe.", a: "Platon", y: "ok. 375 p.n.e." },
  { t: "Cierpliwość jest gorzka, ale jej owoce są słodkie.", a: "Jean-Jacques Rousseau", y: "1762" },
  { t: "Energia i wytrwałość zwyciężają wszystko.", a: "Benjamin Franklin", y: "1750" },
  { t: "Małymi uderzeniami ścina się wielkie dęby.", a: "Benjamin Franklin", y: "1750" },
  { t: "Dobrze wykorzystany dzień daje dobry sen.", a: "Leonardo da Vinci", y: "ok. 1500" },
  { t: "Żelazo rdzewieje z bezczynności, woda stojąca gnije — tak i umysł bez ćwiczenia.", a: "Leonardo da Vinci", y: "ok. 1500" },
  { t: "Wytrwałość to nie długi bieg. To wiele krótkich biegów, jeden po drugim.", a: "Walter Elliot", y: null },
  { t: "Odwaga nie zawsze ryczy. Czasem jest cichym głosem, który mówi: jutro spróbuję znowu.", a: "Mary Anne Radmacher", y: "2009" },
  { t: "Upadłeś siedem razy? Wstań osiem.", a: null, y: "przysłowie japońskie" },
  { t: "Powoli znaczy pewnie, a pewnie znaczy daleko.", a: null, y: null },
  { t: "Najpierw ty tworzysz nawyki. Potem nawyki tworzą ciebie.", a: "John Dryden", y: "1670" },
  { t: "Czego się nie użyje, to się traci.", a: null, y: null },
  { t: "Dobra forma zaczyna się w głowie, przechodzi przez kuchnię i kończy na siłowni.", a: null, y: null },
  { t: "Codzienność wygrywa z intensywnością.", a: null, y: null },
  { t: "Trenuj słabości, aż staną się mocnymi stronami.", a: null, y: null },
  { t: "Nie czekaj na idealny moment. Weź moment i uczyń go idealnym.", a: null, y: null },
  { t: "Sekret zmiany to skupić całą energię nie na walce ze starym, lecz na budowaniu nowego.", a: "Dan Millman", y: "1980" },
  { t: "Zwycięzca nigdy nie rezygnuje, a rezygnujący nigdy nie wygrywa.", a: "Napoleon Hill", y: "1937" },
  { t: "Cokolwiek umysł potrafi wymyślić i w co uwierzyć, to potrafi osiągnąć.", a: "Napoleon Hill", y: "1937" },
  { t: "Nie licz na łatwe życie. Licz na siłę, by udźwignąć trudne.", a: null, y: null },
  { t: "Głód sukcesu musi być większy niż strach przed porażką.", a: "Bill Cosby", y: null },
  { t: "Porażka to przyprawa, która nadaje smak zwycięstwu.", a: "Truman Capote", y: null },
  { t: "Im więcej potu na treningu, tym mniej krwi w boju.", a: null, y: "przysłowie wojskowe" },
  { t: "Zrób dziś coś, za co przyszły ty ci podziękuje.", a: "Sean Patrick Flanery", y: null },
  { t: "Nie musisz widzieć całych schodów. Zrób pierwszy krok.", a: "Martin Luther King", y: "1960" },
  { t: "Jeśli nie umiesz latać — biegnij. Nie umiesz biec — idź. Nie umiesz iść — czołgaj się. Ale cokolwiek robisz, posuwaj się naprzód.", a: "Martin Luther King", y: "1960" },
  { t: "Mierz wysoko: nawet chybiając gwiazdę, trafisz w księżyc.", a: "Norman Vincent Peale", y: "1952" },
  { t: "Człowiek nie jest stworzony do porażki. Człowieka można zniszczyć, ale nie pokonać.", a: "Ernest Hemingway", y: "1952" },
  { t: "To nie góry zdobywamy, lecz samych siebie.", a: "Edmund Hillary", y: "1953" },
  { t: "Ponieważ istnieje.", a: "George Mallory", y: "1923" },
  { t: "Granice istnieją tylko w głowie.", a: null, y: null },
  { t: "Dzisiejszy trening to jutrzejsza siła.", a: null, y: null },
  { t: "Bądź silny — nie dlatego, że życie jest łatwe, ale dlatego, że bywa trudne.", a: null, y: null },
  { t: "Zdrowie to nie wszystko, ale bez zdrowia wszystko jest niczym.", a: "Arthur Schopenhauer", y: "1851" },
  { t: "Ruch jest życiem. Życie jest ruchem.", a: "Moshé Feldenkrais", y: "1972" },
  { t: "Ruch może zastąpić wiele leków, ale żaden lek nie zastąpi ruchu.", a: "Wojciech Oczko", y: "1578" },
  { t: "Lepiej spalić się, niż zardzewieć.", a: "Neil Young", y: "1979" },
  { t: "Życie zaczyna się na końcu strefy komfortu.", a: "Neale Donald Walsch", y: "1998" },
  { t: "Kto chce, szuka sposobu. Kto nie chce, szuka powodu.", a: null, y: null },
  { t: "Trenuj tak, żeby twoje wczorajsze maksimum stało się dzisiejszą rozgrzewką.", a: null, y: null },
  { t: "Sukces w małym daje odwagę do wielkiego.", a: null, y: null },
  { t: "Konsekwencja bije intensywność. Zawsze.", a: null, y: null },
  { t: "Twoja przyszła sylwetka patrzy teraz, co robisz.", a: null, y: null },
  { t: "Silniejszy z każdą serią. Mądrzejszy z każdym błędem.", a: null, y: null },
];

export function dailyQuote(ref = new Date()) {
  const day = Math.floor(ref.getTime() / (24 * 3600 * 1000));
  return QUOTES[day % QUOTES.length];
}
